"""
Django settings for wd_ss project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Tự động nạp các biến môi trường từ file .env nếu tồn tại (Đảm bảo bảo mật khi đẩy lên GitHub)
env_path = BASE_DIR / '.env'
if env_path.exists():
    with open(env_path, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith('#'):
                if '=' in line:
                    key, val = line.split('=', 1)
                    os.environ[key.strip()] = val.strip().strip("'").strip('"')




# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-tqlxfh^vr!6@@3k*@f1@aj%hmc=^^7f5gr6c4at8d6jaoviq1v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'detection',
    'alertupload_rest',
    'django_filters',
    'rest_framework.authtoken',
    'django_extensions',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'wd_ss.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wd_ss.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    # 'default': {
    #    'ENGINE': 'django.db.backends.mysql',
    #    'NAME': os.environ['DB_NAME'],
    #    'USER': os.environ['DB_USER'],
    #    'PASSWORD': os.environ['DB_PASSWORD'],
    #    'HOST': os.environ['DB_HOST'],
    #    'PORT': '3306',
    # }
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR / "static")
]

# Twilio configuration
#
# TWILIO_ACCOUNT_SID = os.environ['TWILIO_ACCOUNT_SID']
# TWILIO_AUTH_TOKEN = os.environ['TWILIO_AUTH_TOKEN']
# TWILIO_NUMBER = os.environ['TWILIO_NUMBER']

# Amazon s3 configuration
#
# AWS_ACCESS_KEY_ID = os.environ['AWS_ACCESS_KEY_ID']
# AWS_SECRET_ACCESS_KEY = os.environ['AWS_SECRET_ACCESS_KEY']
# AWS_STORAGE_BUCKET_NAME = 'uploaded-alerts'
# AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME
# AWS_S3_OBJECT_PARAMETERS = {
#     'CacheControl': 'max-age=86400',
# }
# AWS_LOCATION = 'static'
# PUBLIC_MEDIA_LOCATION = 'media'
# MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{PUBLIC_MEDIA_LOCATION}/'
# DEFAULT_FILE_STORAGE = 'wd_ss.storage_backends.PublicMediaStorage'

MEDIA_ROOT = os.path.join(BASE_DIR, 'static', 'images')


# ==========================================
# KHU VỰC: PHÒNG BƯU ĐIỆN (CẤU HÌNH EMAIL SMTP)
# ==========================================
# Cấu hình kết nối trực tiếp với dịch vụ thư điện tử của Gmail.
# Cho phép ứng dụng Django tự động gửi thư báo động có kèm ảnh khi phát hiện cháy.

# 1. Chọn đối tác chuyển phát: Sử dụng thư viện SMTP tiêu chuẩn của Django
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# 2. Địa chỉ Bưu điện Gmail: Máy chủ SMTP của Google
EMAIL_HOST = 'smtp.gmail.com'

# 3. Cổng bưu điện: Cổng 587 (bảo mật TLS)
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# 4. Địa chỉ hòm thư người gửi: Gmail thực tế của bạn
EMAIL_HOST_USER = 'nguyentainang246@gmail.com'

# 5. Chìa khóa bảo mật: Mật khẩu ứng dụng 16 ký tự (App Password)
# Lưu ý: Tuyệt đối không dùng mật khẩu đăng nhập Gmail thường vì Google chặn lý do bảo mật.
EMAIL_HOST_PASSWORD = 'oonuteejdtqagtfp'


# ==========================================
# KHU VỰC: CẤU HÌNH TELEGRAM BOT
# ==========================================
# Cấu hình Token và Chat ID mặc định cho Bot Telegram nhận cảnh báo.
# Lấy từ biến môi trường (file .env) để bảo mật thông tin khi chia sẻ lên GitHub.
TELEGRAM_BOT_TOKEN = os.environ.get('TELEGRAM_BOT_TOKEN', 'YOUR_TELEGRAM_BOT_TOKEN')
TELEGRAM_CHAT_ID = os.environ.get('TELEGRAM_CHAT_ID', 'YOUR_TELEGRAM_CHAT_ID')




